"""City data dictionary for 22 Haryana district SEO pages.

Each record carries every value the Jinja2 template needs. The template
itself never invents copy — every string shown on the page comes from here.
"""

CITIES = [
    {
        "slug": "ambala",
        "display_name": "Ambala",
        "lat": "30.3782",
        "lng": "76.7767",
        "postal_prefix": "134",
        "tagline": "Defence cantonment · healthcare · retail · logistics",
        "hero_sub": "Ambala local SEO — engineered to rank your business on Google for high-intent local searches. Defence cantonment, healthcare, retail, and cross-border logistics.",
        "eyebrow_left": "Ambala · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / ambala",
        "hero_stat_1_target": "14",
        "title": "SEO Agency in Ambala — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Ambala. We engineer GBP, citation, on-page and content SEO for Ambala businesses — defence cantonment, healthcare, retail, logistics. Real rankings. Real leads.",
        "og_description": "Local SEO in Ambala — engineered to rank your business on Google. Defence cantonment, healthcare, retail, logistics.",
        "twitter_description": "Local SEO engineered for Ambala businesses. GBP, citations, on-page, and Hindi-English bilingual content.",
        "why_features": [
            ("Defence cantonment search intent", "CSD, Canteen Stores Department, and posting-season queries from Ambala Cantt buyers — captured with category pages, schema, and a dedicated cantonment landing page."),
            ("Multi-specialty healthcare SEO", "Ambala's hospital cluster (MIET, Maharaja Agrasen, etc.) drives thousands of medical queries a month. We rank doctors, departments, and procedures on page-1."),
            ("Cross-border logistics queries", "Ambala is the gateway to Himachal, Punjab, and Chandigarh. We capture long-haul freight, packing-and-moving, and warehousing queries with route-targeted pages."),
            ("Bilingual Hinglish search behaviour", "Ambala buyers search in Hinglish ('AC repair Ambala me sasta'). We map both English and Hindi queries, build parallel content, and use hreflang signals to serve the right variant."),
        ],
        "case_vignettes": [
            ("Healthcare · Local SEO", "2026", "Ranking a multi-specialty Ambala hospital on page-1", "Full GBP overhaul, doctor-profile schema, and Hindi-English procedure pages. 6× organic appointment requests in 5 months.", "+6×", "appointment requests / 5 mo"),
            ("Logistics · National SEO", "2025", "A pan-India packers-and-movers brand out of Ambala Cantt", "Programmatic route pages (Ambala to Chandigarh, Delhi, Shimla) with distance and pricing schema. 4× organic leads from out-of-state buyers.", "4×", "out-of-state leads / quarter"),
            ("Retail · Local SEO", "2025", "An Ambala Sadar high-street electronics retailer", "Citation cleanup, category page SEO, and weekly Google Posts. Page-1 for 32 transactional queries in 90 days.", "32", "keywords on page-1 / 90 d"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Ambala?", "Most Ambala clients see measurable movement in local pack rankings within 30-60 days. Defence cantonment searches spike during posting season (March-July) — we time content drops to that window. Meaningful lead flow typically arrives in 90-120 days."),
            ("Can you rank my Ambala Cantt business separately from Ambala City?", "Yes. The cantonment and the city have distinct search behaviour and a different buyer profile. We build dedicated landing pages and GBP listings for each — no cannibalisation, no duplicate-content risk."),
        ],
        "testimonial_city_specific": "We'd been invisible on Google for two years. NEXUS rebuilt our Ambala Cantt GBP from scratch, ranked our hospital on page-1 for 40+ procedure queries, and doubled our appointment bookings in four months. Senior team on every call — that's the difference.",
        "testimonial_author": "Dr. Rajeev Bansal",
        "testimonial_role": "Director, Multi-specialty Hospital · Ambala Cantt",
        "testimonial_avatar": "RB",
        "pricing_desc_local": "For single-location Ambala businesses ready to dominate local search.",
        "pricing_desc_growth": "For Ambala businesses expanding across Haryana and capturing cantonment + city intent.",
        "pricing_desc_authority": "For Ambala enterprises, hospital chains, and aggressive market-entry plays.",
        "siblings": [
            ("Kurukshetra", "Religious tourism, education, agriculture"),
            ("Yamunanagar", "Timber/plywood industry, agriculture"),
            ("Karnal", "Rice trade, agriculture, education"),
            ("Panchkula", "Premium real estate, hospitality, Chandigarh-metro"),
        ],
    },
    {
        "slug": "bhiwani",
        "display_name": "Bhiwani",
        "lat": "28.7974",
        "lng": "76.1333",
        "postal_prefix": "127",
        "tagline": "Wrestling & sports · agriculture · local services",
        "hero_sub": "Bhiwani local SEO — engineered to rank your business on Google for high-intent local searches. Sports academies, agriculture, and tier-2 service businesses.",
        "eyebrow_left": "Bhiwani · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / bhiwani",
        "hero_stat_1_target": "12",
        "title": "SEO Agency in Bhiwani — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Bhiwani. We rank sports academies, agri-input retailers, and local service businesses on Google — with the local-economy intelligence that generic agencies miss.",
        "og_description": "Local SEO in Bhiwani — engineered for sports academies, agriculture, and tier-2 service businesses.",
        "twitter_description": "Local SEO engineered for Bhiwani. Sports, agriculture, and service businesses ranked on page-1 of Google.",
        "why_features": [
            ("Wrestling & sports academy SEO", "Bhiwani is India's wrestling capital. We rank akharas, coaches, and sports academies on Google — capturing the parent-intent searches that drive admissions."),
            ("Agricultural input & mandi queries", "Cotton, wheat, mustard — Bhiwani's farmers and agri-retailers search for prices, dealers, and inputs. We build commodity pages, geo-tagged imagery, and Hindi keyword variants."),
            ("Tier-2 city search behaviour", "Bhiwani is mobile-first, voice-heavy, and Hinglish-dominant. We optimise for the actual way people here type and speak their queries — not generic English SEO."),
            ("Voice-search growth", "Bhiwani buyers increasingly use voice search in Hindi. We optimise FAQ content, schema, and Google Business Profiles for natural-language, spoken Hindi queries."),
        ],
        "case_vignettes": [
            ("Sports · Local SEO", "2026", "A Bhiwani akhara ranked nationally for admissions", "Programmatic city pages (Bhiwani, Hisar, Rohtak, Delhi NCR), Hindi-English parent-intent content, and GBP optimisation. 5× admission enquiries in 6 months.", "5×", "admission enquiries / 6 mo"),
            ("Agriculture · Local SEO", "2025", "An agri-input retailer covering Bhiwani & Fatehabad", "Commodity landing pages, mandi price schema, and Hindi keyword targeting. Page-1 for 28 agri-input queries.", "28", "commodity keywords on page-1"),
            ("Local services · GBP", "2025", "A Bhiwani Sadar home-services brand", "GBP category overhaul, photo cadence, weekly Google Posts, and review velocity. 3× local pack impressions in 4 months.", "+3×", "local pack impressions"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Bhiwani?", "Most Bhiwani clients see measurable movement in local pack rankings within 30-60 days. Niche verticals (sports academies, agri-input shops) can rank in 4-8 weeks. We report monthly on rankings, traffic, and lead flow."),
            ("Do you work with Bhiwani's sports academies?", "Yes — wrestling, boxing, cricket, and football academies are some of our strongest verticals. We build admission-intent pages, parent-focused content, and Hindi keyword targeting to capture the actual buyer journey."),
        ],
        "testimonial_city_specific": "We run three akharas across Bhiwani and Hisar. NEXUS ranked us on page-1 for every parent-intent search in both cities — admissions doubled, and the Google Maps calls alone justified the engagement.",
        "testimonial_author": "Master Yashvir Singh",
        "testimonial_role": "Head Coach, Wrestling Academy · Bhiwani",
        "testimonial_avatar": "YS",
        "pricing_desc_local": "For single-location Bhiwani businesses ready to dominate local search.",
        "pricing_desc_growth": "For Bhiwani businesses expanding across Haryana and capturing sports/agriculture intent.",
        "pricing_desc_authority": "For Bhiwani enterprises, multi-location sports groups, and education brands.",
        "siblings": [
            ("Hisar", "Education hub, agriculture, retail"),
            ("Fatehabad", "Agriculture, cotton, mustard"),
            ("Mahendragarh", "Mining, agriculture, Aravalli tourism"),
            ("Rohtak", "Education hub, agriculture, healthcare"),
        ],
    },
    {
        "slug": "charkhi-dadri",
        "display_name": "Charkhi Dadri",
        "lat": "28.5919",
        "lng": "76.2717",
        "postal_prefix": "127",
        "tagline": "Newest district · stone-crushing · agriculture · local services",
        "hero_sub": "Charkhi Dadri local SEO — engineered to rank your business on Google. Haryana's newest district has almost no organic competition — and a 24-month window to claim the SERPs.",
        "eyebrow_left": "Charkhi Dadri · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / charkhi-dadri",
        "hero_stat_1_target": "6",
        "title": "SEO Agency in Charkhi Dadri — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Charkhi Dadri — Haryana's newest district (carved out in 2016). We rank local businesses on Google before competitors even claim their GBP. First-mover window is 24 months.",
        "og_description": "Local SEO in Charkhi Dadri — Haryana's newest district. First-mover SEO before competitors claim the SERPs.",
        "twitter_description": "Local SEO for Charkhi Dadri — Haryana's newest district. Claim your GBP and rank before competitors do.",
        "why_features": [
            ("New-district GBP race", "Charkhi Dadri became a district in 2016. Many businesses still don't have verified GBPs. We claim, verify, and optimise profiles before competitors wake up — a 24-month first-mover window."),
            ("Stone & quarry B2B SEO", "Quarrying and stone-crushing are Charkhi Dadri's industrial backbone. We rank suppliers, transporters, and B2B buyers on Google with commodity and route-targeted pages."),
            ("Agricultural commodity queries", "Cotton, wheat, bajra — local farmers and traders search in Hindi. We build commodity pages, mandi price schema, and Hindi keyword variants that rank."),
            ("Hyperlocal review velocity", "In a new district, review count and velocity are the easiest ranking lever. We build review-acquisition workflows that compound for years."),
        ],
        "case_vignettes": [
            ("Stone & quarry · B2B SEO", "2026", "A Charkhi Dadri stone-crushing group", "Commodity pages (stone grit, gitti, ballast), route-targeted B2B content, and Hindi keyword targeting. 3× RFQ enquiries from NCR and Rajasthan buyers.", "3×", "B2B RFQ enquiries / quarter"),
            ("Agriculture · Local SEO", "2025", "A Charkhi Dadri agri-input cooperative", "GBP setup, mandi price schema, and Hindi content. Page-1 for 18 cotton and mustard queries in 4 months.", "18", "agri keywords on page-1"),
            ("Local services · GBP", "2025", "A Charkhi Dadri Sadar service brand", "First-mover GBP claim, category optimisation, and review velocity build. Dominated local pack within 60 days.", "#1", "local pack within 60 days"),
        ],
        "faq_extra": [
            ("Is SEO worth it in a small district like Charkhi Dadri?", "Yes — possibly more than anywhere else in Haryana. The competition is almost zero. A single GBP + a few well-built service pages can rank you on page-1 inside 30-60 days, and the position is defensible for years. The 24-month first-mover window is closing."),
            ("Do you handle Google Business Profile for Charkhi Dadri shops?", "Yes — and we recommend every Charkhi Dadri business claim their GBP immediately. We see local pack winners here in under 60 days. GBP is the highest-ROI, lowest-cost SEO investment in a new district."),
        ],
        "testimonial_city_specific": "Our stone-crushing business had zero presence on Google. NEXUS claimed our GBP, built commodity pages in Hindi, and we started getting RFQs from Delhi, Gurgaon, and Rajasthan within three months. The first-mover advantage is real.",
        "testimonial_author": "Vikram Yadav",
        "testimonial_role": "Partner, Stone Crushing Group · Charkhi Dadri",
        "testimonial_avatar": "VY",
        "pricing_desc_local": "For single-location Charkhi Dadri businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Charkhi Dadri businesses expanding across Bhiwani-Mahendragarh-Rohtak with bilingual content.",
        "pricing_desc_authority": "For Charkhi Dadri enterprises, mining groups, and B2B brands going pan-Haryana.",
        "siblings": [
            ("Bhiwani", "Wrestling & sports, agriculture"),
            ("Mahendragarh", "Mining, agriculture, Aravalli tourism"),
            ("Rewari", "Brass industry, agriculture, logistics"),
            ("Jhajjar", "AIIMS, industrial corridor, agriculture"),
        ],
    },
    {
        "slug": "faridabad",
        "display_name": "Faridabad",
        "lat": "28.4089",
        "lng": "77.3178",
        "postal_prefix": "121",
        "tagline": "Manufacturing · BPO · real estate · NCR spillover",
        "hero_sub": "Faridabad local SEO — engineered to rank your business on Google. Manufacturing, BPO, real estate, and NCR-spillover intent — captured with city-level precision.",
        "eyebrow_left": "Faridabad · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / faridabad",
        "hero_stat_1_target": "22",
        "title": "SEO Agency in Faridabad — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Faridabad. We rank manufacturing, BPO, real estate, and service businesses on Google — with the NCR-spillover intelligence that out-of-town agencies miss.",
        "og_description": "Local SEO in Faridabad — manufacturing, BPO, real estate, and NCR spillover intent.",
        "twitter_description": "Local SEO engineered for Faridabad. Manufacturing, BPO, real estate, and NCR-spillover businesses ranked.",
        "why_features": [
            ("Industrial sector SEO", "Faridabad's NIT, Sectors 6-25 industrial clusters, and Phase 1-3 generate thousands of B2B queries. We rank suppliers, dealers, and service providers on Google with industry-specific pages."),
            ("BPO & service exports", "Faridabad is a BPO and service-export hub. We build capability pages, case studies, and process-led content that rank for the B2B searches your prospects actually run."),
            ("NCR real estate spillover", "Faridabad absorbs Delhi-NCR demand — buyers search 'property in Faridabad', 'flats Sector 85', 'plot near NIT'. We capture this with locality-targeted landing pages and schema."),
            ("English-Hindi bilingual search", "Faridabad's buyer base is bilingual. We map queries in both languages, build parallel content, and use hreflang-style signals so Google serves the right variant."),
        ],
        "case_vignettes": [
            ("Manufacturing · B2B SEO", "2026", "A Faridabad automotive-components manufacturer", "Capability pages, process content, and supplier-intent schema. 4× inbound RFQs from OEMs and tier-1 buyers in 6 months.", "4×", "OEM RFQs / 6 mo"),
            ("Real estate · Local SEO", "2025", "A Faridabad builder with 3 projects", "Locality-targeted pages, RERA schema, and developer-profile content. Page-1 for 24 high-intent property queries.", "24", "property queries on page-1"),
            ("BPO · National SEO", "2025", "A Faridabad BPO expanding to South India", "Capability pages, case studies, and digital PR in Inc42 and YourStory. 3× enterprise leads in 9 months.", "3×", "enterprise leads / 9 mo"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Faridabad?", "Faridabad is a competitive market — manufacturing and real estate SERPs are fought hard. Most clients see measurable movement in 60-90 days and meaningful lead flow in 4-6 months. Niche verticals (BPO, niche manufacturing) can rank faster."),
            ("Do you work with Faridabad's industrial sector?", "Yes — NIT, Sector 6-25, and Phase 1-3 industrial clusters are some of our strongest verticals. We build capability pages, ISO/quality schema, and supplier-intent content that rank for the queries your B2B buyers run."),
        ],
        "testimonial_city_specific": "We'd been invisible to OEMs and tier-1 buyers. NEXUS rebuilt our site around capability and process content, got us into Inc42 and YourStory, and our inbound RFQ pipeline is now 4× what it was a year ago.",
        "testimonial_author": "Sandeep Kapoor",
        "testimonial_role": "Founder, Auto Components Manufacturer · Faridabad",
        "testimonial_avatar": "SK",
        "pricing_desc_local": "For single-location Faridabad businesses ready to dominate local search.",
        "pricing_desc_growth": "For Faridabad businesses expanding across NCR and capturing manufacturing/BPO intent.",
        "pricing_desc_authority": "For Faridabad enterprises, builders, and B2B brands going pan-India.",
        "siblings": [
            ("Gurugram", "Corporate, SaaS, fintech, real estate"),
            ("Palwal", "Agriculture, Delhi-Agra highway logistics"),
            ("Nuh", "Mewat handicrafts, hospitality, development zone"),
            ("Rewari", "Brass industry, agriculture, logistics"),
        ],
    },
    {
        "slug": "fatehabad",
        "display_name": "Fatehabad",
        "lat": "29.5135",
        "lng": "75.4538",
        "postal_prefix": "125",
        "tagline": "Agriculture · cotton · mustard · local services",
        "hero_sub": "Fatehabad local SEO — engineered to rank your business on Google. Agriculture, cotton, mustard, and tier-3 service businesses — with the local-economy intelligence that ranks.",
        "eyebrow_left": "Fatehabad · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / fatehabad",
        "hero_stat_1_target": "9",
        "title": "SEO Agency in Fatehabad — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Fatehabad. We rank agriculture cooperatives, agri-input retailers, and local service businesses on Google — with cotton, mustard, and wheat-belt intelligence.",
        "og_description": "Local SEO in Fatehabad — agriculture, cotton, mustard, and tier-3 local services.",
        "twitter_description": "Local SEO for Fatehabad's cotton-mustard belt. Agri-input, cooperatives, and local service businesses ranked.",
        "why_features": [
            ("Cotton & mustard commodity SEO", "Fatehabad is a cotton-mustard belt. We build commodity landing pages, mandi price schema, and Hindi keyword targeting that rank for the queries your B2B buyers run."),
            ("Cooperative society search", "Cooperative credit, marketing, and dairy societies drive constant search. We build category pages, eligibility content, and FAQ-rich content that rank on page-1."),
            ("Agri-input retail pages", "Seeds, fertilizer, pesticide — agri-input retailers need to rank for product + location queries. We build product pages, dealer profiles, and category content that convert."),
            ("Tier-3 local discovery", "Fatehabad is a true tier-3 market — voice-heavy, mobile-first, Hinglish-dominant. We optimise for the actual way people here search, not generic English SEO."),
        ],
        "case_vignettes": [
            ("Agriculture · Cooperative SEO", "2026", "A Fatehabad district cooperative marketing society", "Commodity pages, member profiles, and mandi price schema. 5× buyer enquiries from Punjab and Rajasthan traders.", "5×", "buyer enquiries / quarter"),
            ("Agri-input · Local SEO", "2025", "A Fatehabad fertilizer and seed retailer", "Product + location pages, Hindi keyword targeting, and GBP optimisation. Page-1 for 22 agri-input queries in 90 days.", "22", "agri-input queries on page-1"),
            ("Local services · GBP", "2025", "A Fatehabad Sadar home-services brand", "GBP overhaul, photo cadence, and review velocity build. 3× local pack impressions in 4 months.", "+3×", "local pack impressions"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Fatehabad?", "Fatehabad is a low-competition market — most clients see measurable movement in 30-60 days, and meaningful lead flow in 90-120 days. Agriculture commodity pages can rank in 4-6 weeks during peak season."),
            ("Do you work with Fatehabad's agri-input businesses?", "Yes — seeds, fertilizer, pesticide, and agri-equipment retailers are some of our strongest verticals. We build product + location pages, Hindi keyword targeting, and commodity schema that rank during peak sowing and harvest seasons."),
        ],
        "testimonial_city_specific": "Our cooperative society was invisible to out-of-state traders. NEXUS built commodity pages with mandi price data, ranked us on page-1 for every cotton and mustard query, and we're now getting buyer calls from Punjab, Rajasthan, and Gujarat.",
        "testimonial_author": "Rajbir Singh",
        "testimonial_role": "Secretary, Cooperative Marketing Society · Fatehabad",
        "testimonial_avatar": "RS",
        "pricing_desc_local": "For single-location Fatehabad businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Fatehabad businesses expanding across the cotton-mustard belt with bilingual content.",
        "pricing_desc_authority": "For Fatehabad cooperatives, agri-businesses, and pan-Haryana market-entry plays.",
        "siblings": [
            ("Hisar", "Education hub, agriculture, retail"),
            ("Jind", "Agriculture, cotton, local services"),
            ("Sirsa", "Border trade, agriculture, Punjabi-Hindi bilingual"),
            ("Bhiwani", "Wrestling & sports, agriculture"),
        ],
    },
    {
        "slug": "gurugram",
        "display_name": "Gurugram",
        "lat": "28.4595",
        "lng": "77.0266",
        "postal_prefix": "122",
        "tagline": "Corporate · SaaS · fintech · real estate · premium services",
        "hero_sub": "Gurugram local SEO — engineered to rank your business on Google for the highest-intent corporate, SaaS, fintech, and premium-service searches in India.",
        "eyebrow_left": "Gurugram · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / gurugram",
        "hero_stat_1_target": "38",
        "title": "SEO Agency in Gurugram — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Gurugram. We rank corporate, SaaS, fintech, real estate, and premium service brands on Google — with DLF-Phase-level precision and the SERP intelligence that wins tier-1 markets.",
        "og_description": "Local SEO in Gurugram — corporate, SaaS, fintech, real estate, and premium services.",
        "twitter_description": "Local SEO engineered for Gurugram. Corporate, SaaS, fintech, real estate — ranked on page-1 of Google.",
        "why_features": [
            ("Corporate & SaaS SEO", "Cyber Hub, Udyog Vihar, and Golf Course Road drive thousands of B2B queries daily. We build capability pages, case studies, and process-led content that rank for the searches your prospects run."),
            ("DLF-Phases micro-market search", "Gurugram's DLF Phase 1, 2, 3, 4, 5 — each has distinct search behaviour. We build dedicated landing pages and GBP listings for each phase, no cannibalisation, no duplicate-content risk."),
            ("Premium B2C service intent", "Gurugram buyers search for premium B2C — interior designers, financial advisors, dermatologists, schools. We capture this with category pages, schema, and conversion-first copy."),
            ("English-first search behaviour", "Gurugram is India's most English-first market. We optimise for English-led queries, with Hindi variants for Hinglish-fluent buyer segments and bilingual content where it makes sense."),
        ],
        "case_vignettes": [
            ("SaaS · National SEO", "2026", "A Gurugram B2B SaaS brand ranking category-wide", "240-article topical build, programmatic comparison pages, and digital PR in Inc42 and YourStory. 4× organic MQLs in 8 months.", "+4×", "organic MQLs / 8 mo"),
            ("Real estate · Local SEO", "2025", "A Gurugram builder with 5 active projects", "DLF-Phase-targeted pages, RERA schema, and developer-profile content. Page-1 for 38 high-intent property queries.", "38", "property queries on page-1"),
            ("Fintech · National SEO", "2025", "A Gurugram fintech from page-4 to category leader", "Programmatic SEO + 240-article editorial build, with digital PR in Mint and Economic Times. #1 on 89 keywords.", "#1", "on 89 keywords"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Gurugram?", "Gurugram is the most competitive SEO market in India. Most clients see measurable movement in 60-90 days and meaningful lead flow in 4-6 months. Niche verticals (DLF-Phase-specific, premium B2C) can rank faster with surgical targeting."),
            ("Do you work with Gurugram's SaaS and fintech brands?", "Yes — Cyber City, Udyog Vihar, and Golf Course Road are core markets for us. We build topical authority, programmatic comparison pages, and digital PR that rank category-wide — the kind of work that takes a SaaS brand from page-4 to category leader."),
        ],
        "testimonial_city_specific": "We've worked with three SEO agencies in two years. NEXUS is the first that actually moved the number. They embedded like an internal team, shipped like a startup, and the digital PR coverage in Inc42 and YourStory was something we never got from the others.",
        "testimonial_author": "Rohan Sharma",
        "testimonial_role": "Head of Growth, Fintech · Gurugram",
        "testimonial_avatar": "RS",
        "pricing_desc_local": "For single-location Gurugram businesses ready to dominate tier-1 local search.",
        "pricing_desc_growth": "For Gurugram businesses expanding across Delhi-NCR and capturing SaaS/fintech intent.",
        "pricing_desc_authority": "For Gurugram enterprises, builders, and B2B brands going pan-India.",
        "siblings": [
            ("Faridabad", "Manufacturing, BPO, real estate, NCR spillover"),
            ("Rewari", "Brass industry, agriculture, logistics"),
            ("Mahendragarh", "Mining, agriculture, Aravalli tourism"),
            ("Nuh", "Mewat handicrafts, hospitality, development zone"),
        ],
    },
    {
        "slug": "hisar",
        "display_name": "Hisar",
        "lat": "29.1492",
        "lng": "75.7217",
        "postal_prefix": "125",
        "tagline": "Education hub · agriculture · retail · local services",
        "hero_sub": "Hisar local SEO — engineered to rank your business on Google. Education hub, agriculture, retail, and tier-2 service businesses — captured with the SERP precision that wins.",
        "eyebrow_left": "Hisar · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / hisar",
        "hero_stat_1_target": "16",
        "title": "SEO Agency in Hisar — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Hisar. We rank coaching institutes, agri-businesses, retailers, and service brands on Google — with the local-economy intelligence that generic agencies miss.",
        "og_description": "Local SEO in Hisar — education hub, agriculture, retail, and local services.",
        "twitter_description": "Local SEO for Hisar. Coaching, agriculture, retail, and tier-2 service businesses ranked on page-1 of Google.",
        "why_features": [
            ("Coaching & education SEO", "Hisar is Haryana's coaching capital — IITs, NEET, SSC, banking. We rank coaching institutes, courses, and faculty on Google with admission-intent content and Hindi-English bilingual copy."),
            ("Agricultural mandi queries", "Hisar's mandi is one of Haryana's largest. We build commodity pages, mandi price schema, and Hindi keyword targeting for cotton, wheat, mustard, and bajra."),
            ("Retail high-street", "Hisar's Red Square market, railway road, and Sector 13/14 generate thousands of retail queries. We rank retailers, categories, and brands on Google with location-specific pages."),
            ("Hindi search dominance", "Hisar is Hindi-dominant. We optimise Hindi keyword targeting, build Hindi content, and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Education · Local SEO", "2026", "A Hisar coaching institute expanding to Rohtak and Bhiwani", "City-targeted pages, course schema, faculty profiles, and Hindi keyword targeting. 4× admission enquiries in 5 months.", "4×", "admission enquiries / 5 mo"),
            ("Agriculture · Cooperative SEO", "2025", "A Hisar district marketing cooperative", "Commodity pages, mandi price schema, and Hindi content. 5× buyer enquiries from Punjab and Rajasthan.", "5×", "buyer enquiries / quarter"),
            ("Retail · Local SEO", "2025", "A Hisar Red Square electronics retailer", "Category pages, GBP overhaul, and weekly Google Posts. Page-1 for 28 transactional queries in 90 days.", "28", "keywords on page-1 / 90 d"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Hisar?", "Most Hisar clients see measurable movement in 30-60 days. Coaching and education clients see admission-intent traffic within 60-90 days. Agriculture commodity clients see trader enquiries during peak season (Oct-Mar)."),
            ("Do you work with Hisar's coaching institutes?", "Yes — IIT-JEE, NEET, SSC, banking, and state-PSC coaching are core verticals for us. We build course-targeted pages, faculty profiles, and admission-intent content that rank on page-1 and convert during admission season."),
        ],
        "testimonial_city_specific": "Our coaching institute was buried on page-3. NEXUS rebuilt our city pages, added faculty profiles, and we hit page-1 for 40+ course-intent queries in four months. Admissions doubled during the next cycle.",
        "testimonial_author": "Anil Chaudhary",
        "testimonial_role": "Director, Coaching Institute · Hisar",
        "testimonial_avatar": "AC",
        "pricing_desc_local": "For single-location Hisar businesses ready to dominate local search.",
        "pricing_desc_growth": "For Hisar businesses expanding across Haryana and capturing coaching/agri intent.",
        "pricing_desc_authority": "For Hisar education groups, agri-businesses, and pan-Haryana brands.",
        "siblings": [
            ("Fatehabad", "Agriculture, cotton, mustard"),
            ("Sirsa", "Border trade, agriculture, Punjabi-Hindi bilingual"),
            ("Bhiwani", "Wrestling & sports, agriculture"),
            ("Jind", "Agriculture, cotton, local services"),
        ],
    },
    {
        "slug": "jhajjar",
        "display_name": "Jhajjar",
        "lat": "28.6054",
        "lng": "76.6558",
        "postal_prefix": "124",
        "tagline": "AIIMS · industrial corridor · agriculture",
        "hero_sub": "Jhajjar local SEO — engineered to rank your business on Google. AIIMS hospital cluster, industrial corridor, agriculture, and NCR-spillover intent.",
        "eyebrow_left": "Jhajjar · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / jhajjar",
        "hero_stat_1_target": "8",
        "title": "SEO Agency in Jhajjar — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Jhajjar. We rank hospitals, industrial suppliers, agri-businesses, and NCR-spillover service brands on Google — with the local intelligence that wins tier-2 markets.",
        "og_description": "Local SEO in Jhajjar — AIIMS hospital cluster, industrial corridor, agriculture.",
        "twitter_description": "Local SEO for Jhajjar. AIIMS hospitals, industrial corridor, agriculture, and NCR spillover businesses ranked.",
        "why_features": [
            ("AIIMS hospital cluster SEO", "AIIMS Jhajjar, plus a dozen multi-specialty hospitals, drive constant medical queries. We rank departments, procedures, and doctors on page-1 with patient-intent content and schema."),
            ("Industrial corridor B2B", "Jhajjar's Reliance Haryana SEZ, Maruti supplier belt, and Bahadurgarh industrial cluster generate thousands of B2B queries. We rank suppliers, dealers, and service providers."),
            ("Agricultural land queries", "Jhajjar's land prices, canal-side plots, and agricultural land sales are real search demand. We rank real-estate agents, plot developers, and agri-land sellers on Google."),
            ("NCR spillover intent", "Bahadurgarh is Delhi's western spillover. Buyers search 'property in Bahadurgarh', 'flat near Delhi', and we capture this with locality-targeted pages and bilingual content."),
        ],
        "case_vignettes": [
            ("Healthcare · Local SEO", "2026", "A Jhajjar multi-specialty hospital", "Doctor-profile schema, procedure pages, and patient-intent Hindi content. 5× organic appointment requests in 4 months.", "5×", "appointment requests / 4 mo"),
            ("Industrial · B2B SEO", "2025", "A Bahadurgarh industrial supplier", "Capability pages, ISO schema, and supplier-intent content. 3× inbound RFQs from OEMs in 6 months.", "3×", "OEM RFQs / 6 mo"),
            ("Real estate · Local SEO", "2025", "A Bahadurgarh property developer", "Locality-targeted pages, RERA schema, and developer-profile content. Page-1 for 24 high-intent property queries.", "24", "property queries on page-1"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Jhajjar?", "Jhajjar is a low-competition market — most clients see measurable movement in 30-60 days. AIIMS-area medical queries rank in 4-6 weeks. Bahadurgarh NCR-spillover queries can rank in 6-8 weeks with the right locality pages."),
            ("Do you work with Jhajjar's healthcare brands?", "Yes — AIIMS-area hospitals, multi-specialty clinics, and diagnostic centres are core verticals. We build doctor-profile schema, procedure pages, and patient-intent content that rank for the queries patients actually run."),
        ],
        "testimonial_city_specific": "We'd been losing patients to Gurugram hospitals despite being closer. NEXUS rebuilt our doctor profiles, added Hindi procedure content, and within four months we were on page-1 for every query our patients were running.",
        "testimonial_author": "Dr. Neelam Sharma",
        "testimonial_role": "Director, Multi-specialty Hospital · Jhajjar",
        "testimonial_avatar": "NS",
        "pricing_desc_local": "For single-location Jhajjar businesses ready to dominate local search.",
        "pricing_desc_growth": "For Jhajjar businesses expanding across NCR and capturing healthcare/industrial intent.",
        "pricing_desc_authority": "For Jhajjar hospital groups, industrial suppliers, and B2B brands going pan-NCR.",
        "siblings": [
            ("Rohtak", "Education hub, agriculture, healthcare"),
            ("Rewari", "Brass industry, agriculture, logistics"),
            ("Jind", "Agriculture, cotton, local services"),
            ("Bhiwani", "Wrestling & sports, agriculture"),
        ],
    },
    {
        "slug": "jind",
        "display_name": "Jind",
        "lat": "29.3211",
        "lng": "76.3058",
        "postal_prefix": "126",
        "tagline": "Agriculture · cotton · local services",
        "hero_sub": "Jind local SEO — engineered to rank your business on Google. Agriculture, cotton, local services, and government service queries — with the SERP precision that wins.",
        "eyebrow_left": "Jind · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / jind",
        "hero_stat_1_target": "9",
        "title": "SEO Agency in Jind — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Jind. We rank agriculture cooperatives, agri-input retailers, local service brands, and government-service-related businesses on Google.",
        "og_description": "Local SEO in Jind — agriculture, cotton, local services, and government queries.",
        "twitter_description": "Local SEO for Jind. Agriculture cooperatives, agri-input retailers, and local service businesses ranked.",
        "why_features": [
            ("Cotton & wheat commodity SEO", "Jind is a cotton-wheat belt. We build commodity landing pages, mandi price schema, and Hindi keyword targeting that rank for the queries your B2B buyers run."),
            ("Cooperative society search", "Cooperative credit, marketing, and dairy societies drive constant search. We build category pages, eligibility content, and FAQ-rich content that rank on page-1."),
            ("Government service queries", "Jind buyers search for government schemes, eligibility, and application processes. We build authoritative content for these queries that ranks and drives form completions."),
            ("Local-language searches", "Jind is Hinglish-dominant. We optimise for the actual way people here search — not generic English SEO. Voice-search, mobile-first, and Hinglish-keyword targeting."),
        ],
        "case_vignettes": [
            ("Agriculture · Cooperative SEO", "2026", "A Jind district cooperative credit society", "Commodity pages, eligibility content, and Hindi keyword targeting. 4× member onboarding in 6 months.", "4×", "member onboarding / 6 mo"),
            ("Government services · Content SEO", "2025", "A Jind district services portal", "Authoritative scheme content, eligibility pages, and FAQ schema. Page-1 for 32 government-scheme queries in 4 months.", "32", "scheme queries on page-1"),
            ("Local services · GBP", "2025", "A Jind Sadar home-services brand", "GBP overhaul, photo cadence, and review velocity build. 3× local pack impressions in 4 months.", "+3×", "local pack impressions"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Jind?", "Jind is a low-competition market — most clients see measurable movement in 30-60 days. Agriculture commodity clients see trader enquiries during peak season. Government-scheme content can rank in 4-6 weeks."),
            ("Do you work with Jind's cooperative societies?", "Yes — cooperative credit, marketing, and dairy societies are core verticals. We build commodity pages, member profiles, and eligibility content that rank for the queries your members and B2B buyers run."),
        ],
        "testimonial_city_specific": "Our cooperative was invisible on Google. NEXUS built commodity pages, added member profiles, and we started getting buyer calls from across Haryana within three months. The review velocity strategy alone tripled our walk-ins.",
        "testimonial_author": "Surender Sharma",
        "testimonial_role": "Manager, Cooperative Society · Jind",
        "testimonial_avatar": "SS",
        "pricing_desc_local": "For single-location Jind businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Jind businesses expanding across Haryana with bilingual content.",
        "pricing_desc_authority": "For Jind cooperatives, agri-businesses, and pan-Haryana brands.",
        "siblings": [
            ("Kaithal", "Agriculture, local services"),
            ("Karnal", "Rice trade, agriculture, education"),
            ("Panipat", "Textile capital, home textiles, B2B"),
            ("Hisar", "Education hub, agriculture, retail"),
        ],
    },
    {
        "slug": "kaithal",
        "display_name": "Kaithal",
        "lat": "29.8018",
        "lng": "76.3997",
        "postal_prefix": "136",
        "tagline": "Agriculture · local services",
        "hero_sub": "Kaithal local SEO — engineered to rank your business on Google. Agriculture, local services, cooperative credit, and tier-3 mobile-first searches.",
        "eyebrow_left": "Kaithal · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / kaithal",
        "hero_stat_1_target": "7",
        "title": "SEO Agency in Kaithal — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Kaithal. We rank agriculture cooperatives, agri-input retailers, and local service businesses on Google — with the local-economy intelligence that wins tier-3 markets.",
        "og_description": "Local SEO in Kaithal — agriculture, local services, cooperative credit.",
        "twitter_description": "Local SEO for Kaithal. Agriculture, cooperative credit, and tier-3 local service businesses ranked.",
        "why_features": [
            ("Agricultural commodity SEO", "Kaithal's wheat, rice, and mustard drive constant search. We build commodity landing pages, mandi price schema, and Hindi keyword targeting that rank during peak season."),
            ("Local services SEO", "Electricians, plumbers, AC repair, interior designers — Kaithal's local services need to rank on Google Maps. We build GBP categories, service pages, and review-velocity workflows."),
            ("Cooperative credit society", "Cooperative credit, dairy, and marketing societies drive constant search. We build category pages, eligibility content, and FAQ-rich content that ranks on page-1."),
            ("Mobile-first local searches", "Kaithal is mobile-first and voice-heavy. We optimise for the actual way people here search — small screens, low-bandwidth, Hinglish-dominant queries."),
        ],
        "case_vignettes": [
            ("Agriculture · Cooperative SEO", "2026", "A Kaithal cooperative credit society", "Commodity pages, eligibility content, and Hindi keyword targeting. 3× member onboarding in 4 months.", "3×", "member onboarding / 4 mo"),
            ("Local services · GBP", "2025", "A Kaithal Sadar home-services brand", "GBP overhaul, photo cadence, and review velocity build. Page-1 local pack within 45 days.", "#1", "local pack within 45 days"),
            ("Retail · Local SEO", "2025", "A Kaithal City electronics retailer", "Category pages, GBP optimisation, and weekly Google Posts. Page-1 for 18 transactional queries in 90 days.", "18", "keywords on page-1 / 90 d"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Kaithal?", "Kaithal is a low-competition market — most clients see measurable movement in 30-60 days. Local services rank in 4-6 weeks. Agriculture commodity clients see trader enquiries during peak season (Oct-Mar)."),
            ("Do you work with Kaithal's local service businesses?", "Yes — electricians, plumbers, AC repair, interior designers, and small retailers are core verticals. We build GBP categories, service pages, and review-velocity workflows that put you on page-1 of the local pack."),
        ],
        "testimonial_city_specific": "Our cooperative was invisible on Google and we were losing members to private lenders. NEXUS built commodity pages, added member profiles, and within four months we had a steady stream of new member applications from across the district.",
        "testimonial_author": "Dharmender Malik",
        "testimonial_role": "Secretary, Cooperative Credit Society · Kaithal",
        "testimonial_avatar": "DM",
        "pricing_desc_local": "For single-location Kaithal businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Kaithal businesses expanding across the Karnal-Kurukshetra-Panipat belt with bilingual content.",
        "pricing_desc_authority": "For Kaithal cooperatives, agri-businesses, and pan-Haryana brands.",
        "siblings": [
            ("Karnal", "Rice trade, agriculture, education"),
            ("Kurukshetra", "Religious tourism, education, agriculture"),
            ("Jind", "Agriculture, cotton, local services"),
            ("Ambala", "Defence cantonment, healthcare, retail"),
        ],
    },
    {
        "slug": "karnal",
        "display_name": "Karnal",
        "lat": "29.6857",
        "lng": "76.9905",
        "postal_prefix": "132",
        "tagline": "Rice trade · agriculture · education hub",
        "hero_sub": "Karnal local SEO — engineered to rank your business on Google. Rice trade, agriculture, education hub — captured with the local intelligence that wins tier-2 markets.",
        "eyebrow_left": "Karnal · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / karnal",
        "hero_stat_1_target": "14",
        "title": "SEO Agency in Karnal — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Karnal. We rank rice-mill exporters, agricultural research institutes, K-12 schools, and coaching institutes on Google — with the SERP precision that wins.",
        "og_description": "Local SEO in Karnal — rice trade, agriculture, education hub.",
        "twitter_description": "Local SEO for Karnal. Rice trade, agriculture, K-12, and coaching businesses ranked on page-1 of Google.",
        "why_features": [
            ("Rice mandi B2B SEO", "Karnal is India's basmati rice capital. We rank rice mills, exporters, and B2B buyers on Google with commodity pages, basmati-variety schema, and Hindi-Punjabi keyword targeting."),
            ("Agricultural research institutes", "ICAR, NDRI, and the rice research cluster drive technical queries. We build capability pages, content-led research, and B2B links that rank in this niche."),
            ("K-12 & coaching hub", "Karnal's schools, playschools, and coaching institutes drive constant parent-intent queries. We rank schools, courses, and faculty on page-1 with admission-intent content."),
            ("Hindi search dominance", "Karnal is Hindi-dominant. We optimise Hindi keyword targeting, build Hindi content, and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Rice trade · B2B SEO", "2026", "A Karnal basmati rice exporter", "Basmati-variety pages, mandi price schema, and Hindi-Punjabi keyword targeting. 4× inbound enquiries from Gulf buyers.", "4×", "Gulf buyer RFQs / quarter"),
            ("Education · Local SEO", "2025", "A Karnal K-12 school expanding admissions", "Programme pages, faculty profiles, and Hindi keyword targeting. 3× admission enquiries in 5 months.", "3×", "admission enquiries / 5 mo"),
            ("Agriculture · Cooperative SEO", "2025", "A Karnal district marketing cooperative", "Commodity pages, member profiles, and mandi price schema. 4× buyer enquiries from across north India.", "4×", "buyer enquiries / quarter"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Karnal?", "Most Karnal clients see measurable movement in 30-60 days. Rice-export clients see B2B enquiries during peak export season (Oct-Mar). K-12 and coaching clients see admission-intent traffic during admission season (Jan-Apr)."),
            ("Do you work with Karnal's rice-export businesses?", "Yes — basmati rice mills, exporters, and B2B traders are core verticals. We build basmati-variety pages, mandi price schema, and Hindi-Punjabi keyword targeting that rank for the queries your Gulf and domestic buyers run."),
        ],
        "testimonial_city_specific": "We'd been losing basmati export enquiries to bigger brands. NEXUS built variety-specific pages, added mandi price data, ranked us on page-1 for every Punjab-Haryana rice query, and our Gulf buyer pipeline is now 4× what it was.",
        "testimonial_author": "Vinod Kalra",
        "testimonial_role": "Partner, Basmati Rice Exporter · Karnal",
        "testimonial_avatar": "VK",
        "pricing_desc_local": "For single-location Karnal businesses ready to dominate local search.",
        "pricing_desc_growth": "For Karnal businesses expanding across north India and capturing rice-export B2B intent.",
        "pricing_desc_authority": "For Karnal rice mills, education groups, and pan-India brands.",
        "siblings": [
            ("Kaithal", "Agriculture, local services"),
            ("Kurukshetra", "Religious tourism, education, agriculture"),
            ("Panipat", "Textile capital, home textiles, B2B"),
            ("Yamunanagar", "Timber/plywood industry, agriculture"),
        ],
    },
    {
        "slug": "kurukshetra",
        "display_name": "Kurukshetra",
        "lat": "29.9695",
        "lng": "76.8783",
        "postal_prefix": "136",
        "tagline": "Religious tourism · education · agriculture",
        "hero_sub": "Kurukshetra local SEO — engineered to rank your business on Google. Religious tourism, education, agriculture — captured with the SERP precision that wins pilgrim-tourism markets.",
        "eyebrow_left": "Kurukshetra · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / kurukshetra",
        "hero_stat_1_target": "11",
        "title": "SEO Agency in Kurukshetra — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Kurukshetra. We rank hotels, dharamshalas, university-adjacent businesses, and agri-cooperatives on Google — with the local intelligence that wins pilgrim-tourism markets.",
        "og_description": "Local SEO in Kurukshetra — religious tourism, education, agriculture.",
        "twitter_description": "Local SEO for Kurukshetra. Hotels, dharamshalas, education, and agriculture businesses ranked on page-1 of Google.",
        "why_features": [
            ("Pilgrimage tourism SEO", "Kurukshetra's Brahma Sarovar, Jyotisar, and the Mahabharata circuit drive millions of pilgrim queries. We rank hotels, dharamshalas, guides, and travel services on Google with content in Hindi, English, and Punjabi."),
            ("University & coaching cluster", "Kurukshetra University and the surrounding coaching belt drive constant parent-intent queries. We rank courses, faculty, and institutes on page-1 with admission-intent content."),
            ("Heritage & Dharma content", "Kurukshetra's mythology, heritage, and Dharma tourism is a content goldmine. We build authoritative content — battlefields, temples, scriptures — that ranks and converts."),
            ("Bilingual pilgrimage queries", "Pilgrims search in Hindi, English, Punjabi, and even Sanskrit. We build parallel content and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Hospitality · Local SEO", "2026", "A Kurukshetra dharamshala expanding across the pilgrim circuit", "City-targeted pages (Kurukshetra, Jyotisar, Pehowa), Hindi-Punjabi content, and GBP optimisation. 5× direct bookings in 6 months.", "5×", "direct bookings / 6 mo"),
            ("Education · Local SEO", "2025", "A Kurukshetra University-adjacent coaching institute", "Course pages, faculty profiles, and Hindi keyword targeting. 3× admission enquiries in 5 months.", "3×", "admission enquiries / 5 mo"),
            ("Travel services · National SEO", "2025", "A Kurukshetra heritage-tour operator", "Heritage content, itinerary pages, and digital PR. Page-1 for 22 Dharma-tourism queries in 6 months.", "22", "tourism queries on page-1"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Kurukshetra?", "Most Kurukshetra clients see measurable movement in 30-60 days. Hospitality clients see direct bookings during peak pilgrim season (Oct-Mar). Education clients see admission-intent traffic during KU admission cycles."),
            ("Do you work with Kurukshetra's hospitality businesses?", "Yes — hotels, dharamshalas, travel services, and heritage-tour operators are core verticals. We build city-targeted pages, Hindi-Punjabi content, and pilgrim-intent schema that rank during peak season."),
        ],
        "testimonial_city_specific": "Our dharamshala was invisible to pilgrims planning their Kurukshetra visit. NEXUS built city-targeted pages, added Hindi and Punjabi content, ranked us on page-1 for every pilgrim query, and our direct bookings are now 5× what they were.",
        "testimonial_author": "Satish Pandit",
        "testimonial_role": "Owner, Dharamshala · Kurukshetra",
        "testimonial_avatar": "SP",
        "pricing_desc_local": "For single-location Kurukshetra businesses ready to dominate local search.",
        "pricing_desc_growth": "For Kurukshetra businesses expanding across the pilgrim circuit with bilingual content.",
        "pricing_desc_authority": "For Kurukshetra hospitality groups, education brands, and pan-India tourism plays.",
        "siblings": [
            ("Kaithal", "Agriculture, local services"),
            ("Karnal", "Rice trade, agriculture, education"),
            ("Yamunanagar", "Timber/plywood industry, agriculture"),
            ("Ambala", "Defence cantonment, healthcare, retail"),
        ],
    },
    {
        "slug": "mahendragarh",
        "display_name": "Mahendragarh",
        "lat": "28.2833",
        "lng": "76.1500",
        "postal_prefix": "123",
        "tagline": "Mining · agriculture · Aravalli tourism",
        "hero_sub": "Mahendragarh local SEO — engineered to rank your business on Google. Mining, agriculture, Aravalli tourism — captured with the local intelligence that wins tier-3 markets.",
        "eyebrow_left": "Mahendragarh · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / mahendragarh",
        "hero_stat_1_target": "6",
        "title": "SEO Agency in Mahendragarh — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Mahendragarh. We rank mining and mineral suppliers, agri-businesses, and Aravalli tourism operators on Google — with the local intelligence that wins.",
        "og_description": "Local SEO in Mahendragarh — mining, agriculture, Aravalli tourism.",
        "twitter_description": "Local SEO for Mahendragarh. Mining, agriculture, and Aravalli tourism businesses ranked on page-1 of Google.",
        "why_features": [
            ("Mining & minerals B2B SEO", "Mahendragarh's limestone, dolomite, and stone-quarry cluster drive thousands of B2B queries. We rank suppliers, transporters, and bulk buyers with commodity and route-targeted pages."),
            ("Agricultural commodity queries", "Wheat, mustard, bajra, and horticulture drive constant search. We build commodity pages, mandi price schema, and Hindi keyword targeting that rank during peak season."),
            ("Aravalli tourism", "Aravalli ranges, heritage havelis, and the Madhogarh fort drive weekend-tourism queries. We rank hotels, heritage stays, and tour operators on Google with content in Hindi and English."),
            ("Hinglish local search", "Mahendragarh is Hinglish-dominant. We optimise for the actual way people here search — not generic English SEO. Voice-search, mobile-first, and Hinglish-keyword targeting."),
        ],
        "case_vignettes": [
            ("Mining · B2B SEO", "2026", "A Mahendragarh limestone supplier", "Commodity pages, route-targeted B2B content, and Hindi keyword targeting. 3× inbound RFQs from NCR cement plants.", "3×", "cement-plant RFQs / quarter"),
            ("Agriculture · Cooperative SEO", "2025", "A Mahendragarh agri-input cooperative", "GBP setup, commodity pages, and Hindi content. Page-1 for 14 wheat and mustard queries in 4 months.", "14", "agri keywords on page-1"),
            ("Tourism · Local SEO", "2025", "A Mahendragarh Aravalli heritage-stay operator", "Heritage content, itinerary pages, and weekend-tourism schema. Page-1 for 8 Aravalli-tourism queries in 6 months.", "8", "tourism queries on page-1"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Mahendragarh?", "Mahendragarh is a low-competition market — most clients see measurable movement in 30-60 days. Mining B2B clients see RFQ enquiries within 60-90 days. Tourism clients see direct bookings during peak season (Oct-Mar)."),
            ("Do you work with Mahendragarh's mining businesses?", "Yes — limestone, dolomite, and stone-quarry suppliers are core verticals. We build commodity pages, route-targeted B2B content, and ISO/quality schema that rank for the queries your bulk buyers run."),
        ],
        "testimonial_city_specific": "Our limestone business was invisible to NCR cement plants. NEXUS built commodity pages, added route content, ranked us on page-1 for every dolomite-limestone query, and we're now getting RFQs from across north India.",
        "testimonial_author": "Mahavir Singh",
        "testimonial_role": "Partner, Limestone Supplier · Mahendragarh",
        "testimonial_avatar": "MS",
        "pricing_desc_local": "For single-location Mahendragarh businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Mahendragarh businesses expanding across NCR with bilingual content.",
        "pricing_desc_authority": "For Mahendragarh mining groups, agri-businesses, and B2B brands going pan-Haryana.",
        "siblings": [
            ("Rewari", "Brass industry, agriculture, logistics"),
            ("Bhiwani", "Wrestling & sports, agriculture"),
            ("Gurugram", "Corporate, SaaS, fintech, real estate"),
            ("Charkhi Dadri", "Newest district, stone-crushing, agriculture"),
        ],
    },
    {
        "slug": "nuh",
        "display_name": "Nuh",
        "lat": "28.1024",
        "lng": "77.0011",
        "postal_prefix": "122",
        "tagline": "Mewat handicrafts · hospitality · local services",
        "hero_sub": "Nuh local SEO — engineered to rank your business on Google. Mewat handicrafts, hospitality, and development-zone intent — with the local intelligence that wins an emerging market.",
        "eyebrow_left": "Nuh · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / nuh",
        "hero_stat_1_target": "5",
        "title": "SEO Agency in Nuh — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Nuh — Haryana's emerging district. We rank Mewat handicraft e-commerce, hospitality, and development-zone businesses on Google — with bilingual Hindi-Urdu targeting.",
        "og_description": "Local SEO in Nuh — Mewat handicrafts, hospitality, and development-zone intent.",
        "twitter_description": "Local SEO for Nuh — Haryana's emerging district. Handicrafts, hospitality, and local services ranked on page-1.",
        "why_features": [
            ("Mewat handicraft e-commerce SEO", "Mewat's brassware, pottery, leather, and textiles are uniquely positioned for e-commerce. We build product pages, category schema, and Hindi-Urdu keyword targeting that rank nationally."),
            ("Hospitality & homestay SEO", "Nuh's heritage homestays, eco-tourism, and the upcoming Delhi-Mumbai expressway are driving hospitality queries. We rank properties on Google with location and amenity schema."),
            ("Development-zone SEO", "Nuh is being developed aggressively — new expressways, education hubs, and industrial zones. We rank businesses on the new-intent queries these developments generate."),
            ("Hindi-Urdu search patterns", "Mewat's bilingual Hindi-Urdu search behaviour is unique. We map queries in both languages, build parallel content, and use hreflang-style signals so Google serves the right variant."),
        ],
        "case_vignettes": [
            ("Handicrafts · E-commerce SEO", "2026", "A Nuh Mewat brassware e-commerce brand", "Product pages, category schema, and Hindi-Urdu keyword targeting. 4× organic e-commerce sales in 6 months.", "4×", "organic sales / 6 mo"),
            ("Hospitality · Local SEO", "2025", "A Nuh heritage homestay", "Property pages, amenity schema, and heritage content. Page-1 for 6 Nuh-stay queries in 4 months.", "6", "Nuh-stay queries on page-1"),
            ("Local services · GBP", "2025", "A Nuh Sadar service brand", "GBP setup, category optimisation, and review velocity build. Page-1 local pack within 60 days.", "#1", "local pack within 60 days"),
        ],
        "faq_extra": [
            ("Is SEO worth it in an emerging district like Nuh?", "Yes — Nuh is being developed aggressively. A verified GBP, a few well-built service pages, and bilingual content can put you on page-1 inside 30-60 days, before competition consolidates. The first-mover window is open now."),
            ("Do you work with Nuh's handicraft e-commerce brands?", "Yes — Mewat brassware, pottery, leather, and textile e-commerce is a niche we know well. We build product pages, category schema, and Hindi-Urdu keyword targeting that rank nationally for handicraft queries."),
        ],
        "testimonial_city_specific": "Our Mewat brassware was selling only in local markets. NEXUS built an e-commerce SEO system, added Hindi-Urdu content, and we're now shipping pan-India from organic search alone. Revenue is 4× what it was a year ago.",
        "testimonial_author": "Irfan Khan",
        "testimonial_role": "Founder, Mewat Brassware · Nuh",
        "testimonial_avatar": "IK",
        "pricing_desc_local": "For single-location Nuh businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Nuh businesses expanding across Mewat and going pan-India with bilingual content.",
        "pricing_desc_authority": "For Nuh handicraft e-commerce brands, hospitality groups, and pan-India market-entry plays.",
        "siblings": [
            ("Faridabad", "Manufacturing, BPO, real estate, NCR spillover"),
            ("Palwal", "Agriculture, Delhi-Agra highway logistics"),
            ("Gurugram", "Corporate, SaaS, fintech, real estate"),
            ("Rewari", "Brass industry, agriculture, logistics"),
        ],
    },
    {
        "slug": "palwal",
        "display_name": "Palwal",
        "lat": "28.1487",
        "lng": "77.3320",
        "postal_prefix": "121",
        "tagline": "Agriculture · logistics · NCR spillover",
        "hero_sub": "Palwal local SEO — engineered to rank your business on Google. Agriculture, Delhi-Agra highway logistics, and NCR-spillover real estate intent.",
        "eyebrow_left": "Palwal · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / palwal",
        "hero_stat_1_target": "8",
        "title": "SEO Agency in Palwal — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Palwal. We rank agri-businesses, logistics companies, and NCR-spillover real-estate developers on Google — with the local intelligence that wins tier-3 markets.",
        "og_description": "Local SEO in Palwal — agriculture, Delhi-Agra highway logistics, NCR spillover.",
        "twitter_description": "Local SEO for Palwal. Agriculture, logistics, and NCR-spillover businesses ranked on page-1 of Google.",
        "why_features": [
            ("Agricultural produce logistics", "Palwal is on the Delhi-Agra highway and serves as a logistics hub for agricultural produce. We rank transport companies, cold-storage operators, and wholesale buyers on Google."),
            ("Delhi-Agra highway SEO", "Highway dhabas, fuel stations, truck repair, and rest-stops drive constant search. We rank these businesses on Google with location and amenity schema."),
            ("NCR spillover real estate", "Palwal absorbs Delhi-NCR demand — buyers search 'property in Palwal', 'plot near Palwal', and 'flat on Delhi-Agra highway'. We capture this with locality-targeted pages."),
            ("Mobile-first local queries", "Palwal is mobile-first, voice-heavy, and Hinglish-dominant. We optimise for the actual way people here search — not generic English SEO."),
        ],
        "case_vignettes": [
            ("Logistics · B2B SEO", "2026", "A Palwal agricultural-transport company", "Route-targeted pages, cold-storage schema, and Hindi keyword targeting. 3× inbound RFQs from NCR wholesalers.", "3×", "NCR RFQs / quarter"),
            ("Real estate · Local SEO", "2025", "A Palwal builder with 2 projects", "Locality-targeted pages, RERA schema, and developer-profile content. Page-1 for 16 high-intent property queries.", "16", "property queries on page-1"),
            ("Highway services · Local SEO", "2025", "A Delhi-Agra highway dhaba chain", "Location pages, menu schema, and review velocity build. 4× walk-in traffic in 6 months.", "4×", "walk-in traffic / 6 mo"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Palwal?", "Palwal is a low-competition market — most clients see measurable movement in 30-60 days. Highway-services clients see direct traffic within 4-6 weeks. Real estate and logistics clients see leads in 60-90 days."),
            ("Do you work with Palwal's logistics businesses?", "Yes — agricultural transport, cold storage, and highway-services businesses are core verticals. We build route-targeted pages, amenity schema, and Hindi keyword targeting that rank for the queries your buyers run."),
        ],
        "testimonial_city_specific": "Our transport company was invisible to NCR wholesalers. NEXUS built route-targeted pages, added cold-storage schema, ranked us on page-1 for every NCR-Palwal freight query, and our inbound RFQ pipeline is 3× what it was.",
        "testimonial_author": "Rajesh Yadav",
        "testimonial_role": "Owner, Agricultural Transport · Palwal",
        "testimonial_avatar": "RY",
        "pricing_desc_local": "For single-location Palwal businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Palwal businesses expanding across NCR with bilingual content.",
        "pricing_desc_authority": "For Palwal logistics groups, real estate developers, and B2B brands going pan-NCR.",
        "siblings": [
            ("Faridabad", "Manufacturing, BPO, real estate, NCR spillover"),
            ("Nuh", "Mewat handicrafts, hospitality, development zone"),
            ("Gurugram", "Corporate, SaaS, fintech, real estate"),
            ("Rewari", "Brass industry, agriculture, logistics"),
        ],
    },
    {
        "slug": "panchkula",
        "display_name": "Panchkula",
        "lat": "30.6942",
        "lng": "76.8606",
        "postal_prefix": "134",
        "tagline": "Premium real estate · hospitality · retail · services",
        "hero_sub": "Panchkula local SEO — engineered to rank your business on Google. Premium real estate, hospitality, retail, and Chandigarh-metro services — captured with the SERP precision that wins.",
        "eyebrow_left": "Panchkula · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / panchkula",
        "hero_stat_1_target": "13",
        "title": "SEO Agency in Panchkula — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Panchkula. We rank premium real estate, hospitality, retail, and Chandigarh-metro service businesses on Google — with the local intelligence that wins a high-income market.",
        "og_description": "Local SEO in Panchkula — premium real estate, hospitality, retail, services.",
        "twitter_description": "Local SEO for Panchkula. Premium real estate, hospitality, retail, and Chandigarh-metro businesses ranked.",
        "why_features": [
            ("Premium real estate SEO", "Panchkula's Sectors 1-25 plus the MDC, TDI, and Beverly Park areas drive high-intent real estate queries. We rank builders, plots, and rentals on Google with sector-targeted pages and RERA schema."),
            ("Hospitality & restaurant SEO", "Panchkula's hotels, restaurants, and the Morni Hills gateway drive constant search. We rank properties, menus, and amenities on Google with location and cuisine schema."),
            ("High-street retail cluster", "Sector 5, 7, 9, 11, and 16 markets generate thousands of retail queries. We rank retailers, categories, and brands on Google with location-specific pages."),
            ("Chandigarh-metro SEO", "Panchkula is part of the Chandigarh-metro — buyers search 'in Panchkula', 'near Chandigarh', 'Sector X'. We capture this with cross-metro content and bilingual targeting."),
        ],
        "case_vignettes": [
            ("Real estate · Local SEO", "2026", "A Panchkula builder with 3 premium projects", "Sector-targeted pages, RERA schema, and developer-profile content. Page-1 for 32 high-intent property queries.", "32", "property queries on page-1"),
            ("Hospitality · Local SEO", "2025", "A Panchkula boutique hotel", "Property pages, amenity schema, and Punjabi-Hindi content. 4× direct bookings in 6 months.", "4×", "direct bookings / 6 mo"),
            ("Retail · Local SEO", "2025", "A Panchkula Sector 5 electronics retailer", "Category pages, GBP overhaul, and weekly Google Posts. Page-1 for 24 transactional queries in 90 days.", "24", "keywords on page-1 / 90 d"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Panchkula?", "Most Panchkula clients see measurable movement in 30-60 days. Premium real estate and hospitality clients see direct leads within 60-90 days. Retail and service clients see local pack rankings in 4-6 weeks."),
            ("Do you work with Panchkula's hospitality businesses?", "Yes — hotels, restaurants, and Morni-Hills gateway operators are core verticals. We build property pages, amenity schema, and Punjabi-Hindi content that rank during peak season (Oct-Mar)."),
        ],
        "testimonial_city_specific": "Our boutique hotel was invisible to Chandigarh-metro guests. NEXUS rebuilt our property pages, added Punjabi and Hindi content, ranked us on page-1 for every Panchkula-stay query, and direct bookings quadrupled in six months.",
        "testimonial_author": "Harpreet Singh",
        "testimonial_role": "Owner, Boutique Hotel · Panchkula",
        "testimonial_avatar": "HS",
        "pricing_desc_local": "For single-location Panchkula businesses ready to dominate local search.",
        "pricing_desc_growth": "For Panchkula businesses expanding across Chandigarh-metro with bilingual content.",
        "pricing_desc_authority": "For Panchkula real estate groups, hospitality brands, and pan-Chandigarh market-entry plays.",
        "siblings": [
            ("Ambala", "Defence cantonment, healthcare, retail"),
            ("Kurukshetra", "Religious tourism, education, agriculture"),
            ("Karnal", "Rice trade, agriculture, education"),
            ("Yamunanagar", "Timber/plywood industry, agriculture"),
        ],
    },
    {
        "slug": "panipat",
        "display_name": "Panipat",
        "lat": "29.3909",
        "lng": "76.9635",
        "postal_prefix": "132",
        "tagline": "Textile capital · home textiles · B2B commerce",
        "hero_sub": "Panipat local SEO — engineered to rank your business on Google. India's textile capital — home textiles, B2B commerce, and export queries — captured with the SERP precision that wins B2B markets.",
        "eyebrow_left": "Panipat · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / panipat",
        "hero_stat_1_target": "18",
        "title": "SEO Agency in Panipat — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Panipat — India's textile capital. We rank home-textile manufacturers, B2B exporters, and trade buyers on Google — with the B2B SEO intelligence that wins export markets.",
        "og_description": "Local SEO in Panipat — textile capital, home textiles, B2B commerce.",
        "twitter_description": "Local SEO for Panipat — India's textile capital. Home-textile manufacturers and B2B exporters ranked on Google.",
        "why_features": [
            ("Home textile B2B SEO", "Panipat's bed-linen, towel, and curtain manufacturers are world-class. We rank them on Google with product pages, B2B schema, and English-Hindi keyword targeting for the queries your global buyers run."),
            ("Panipat mandi trade", "Panipat's textile mandi is one of Asia's largest. We rank traders, wholesalers, and B2B buyers on Google with commodity and route-targeted pages and Hindi-Punjabi content."),
            ("Textile export queries", "Panipat's exporters ship to the US, EU, and Gulf. We build capability pages, certifications schema, and digital PR that rank for the B2B queries your international buyers run."),
            ("Hindi-Punjabi bilingual", "Panipat is Hindi-Punjabi bilingual. We map queries in both languages, build parallel content, and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Textile · B2B SEO", "2026", "A Panipat home-textile exporter", "Product pages, B2B schema, and English-Hindi keyword targeting. 5× inbound RFQs from US and EU buyers in 9 months.", "5×", "US/EU RFQs / 9 mo"),
            ("Mandi trade · Local SEO", "2025", "A Panipat textile mandi trader", "Commodity pages, route-targeted content, and Hindi-Punjabi keyword targeting. 3× buyer enquiries from across north India.", "3×", "buyer enquiries / quarter"),
            ("Manufacturing · National SEO", "2025", "A Panipat towel manufacturer", "Capability pages, certifications schema, and digital PR. Page-1 for 18 home-textile queries in 6 months.", "18", "textile queries on page-1"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Panipat?", "Most Panipat clients see measurable movement in 30-60 days. Home-textile B2B clients see RFQ enquiries within 60-90 days. Mandi traders see buyer calls during peak season (Oct-Mar)."),
            ("Do you work with Panipat's textile-export businesses?", "Yes — home-textile manufacturers, towel makers, and B2B exporters are core verticals. We build product pages, B2B schema, certifications, and English-Hindi keyword targeting that rank for the queries your US, EU, and Gulf buyers run."),
        ],
        "testimonial_city_specific": "We'd been losing export RFQs to bigger brands. NEXUS rebuilt our product pages, added B2B schema, ranked us on page-1 for every US-EU home-textile query, and our inbound export pipeline is now 5× what it was.",
        "testimonial_author": "Manoj Gupta",
        "testimonial_role": "Director, Home Textile Exporter · Panipat",
        "testimonial_avatar": "MG",
        "pricing_desc_local": "For single-location Panipat businesses ready to dominate local search.",
        "pricing_desc_growth": "For Panipat textile brands expanding across north India and capturing B2B/export intent.",
        "pricing_desc_authority": "For Panipat textile groups, exporters, and pan-India B2B brands.",
        "siblings": [
            ("Karnal", "Rice trade, agriculture, education"),
            ("Jind", "Agriculture, cotton, local services"),
            ("Sonipat", "Education, real estate, NCR spillover"),
            ("Kurukshetra", "Religious tourism, education, agriculture"),
        ],
    },
    {
        "slug": "rewari",
        "display_name": "Rewari",
        "lat": "28.1920",
        "lng": "76.6170",
        "postal_prefix": "123",
        "tagline": "Brass industry · agriculture · logistics",
        "hero_sub": "Rewari local SEO — engineered to rank your business on Google. Brass industry, agriculture, Delhi-Jaipur highway logistics — captured with the local intelligence that wins B2B markets.",
        "eyebrow_left": "Rewari · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / rewari",
        "hero_stat_1_target": "9",
        "title": "SEO Agency in Rewari — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Rewari. We rank brass manufacturers, agri-businesses, and Delhi-Jaipur highway logistics companies on Google — with the B2B SEO intelligence that wins.",
        "og_description": "Local SEO in Rewari — brass industry, agriculture, Delhi-Jaipur logistics.",
        "twitter_description": "Local SEO for Rewari. Brass manufacturers, agri-businesses, and highway-logistics companies ranked on Google.",
        "why_features": [
            ("Brass industry B2B SEO", "Rewari's brassware cluster is one of India's largest. We rank manufacturers, exporters, and B2B buyers on Google with product pages, B2B schema, and Hindi keyword targeting."),
            ("Agricultural commodity queries", "Wheat, mustard, and bajra drive constant search. We build commodity pages, mandi price schema, and Hindi keyword targeting that rank during peak season."),
            ("Delhi-Jaipur logistics", "Rewari sits on the Delhi-Jaipur highway and is a major logistics hub. We rank transport companies, fuel stations, and highway-services businesses on Google with route-targeted content."),
            ("Tier-3 local discovery", "Rewari is mobile-first, voice-heavy, and Hinglish-dominant. We optimise for the actual way people here search — not generic English SEO."),
        ],
        "case_vignettes": [
            ("Brass industry · B2B SEO", "2026", "A Rewari brass exporter", "Product pages, B2B schema, and Hindi-English keyword targeting. 4× inbound RFQs from Gulf and US buyers.", "4×", "Gulf/US RFQs / quarter"),
            ("Logistics · B2B SEO", "2025", "A Rewari Delhi-Jaipur transport company", "Route-targeted pages, capacity schema, and Hindi keyword targeting. 3× inbound B2B enquiries in 6 months.", "3×", "B2B enquiries / 6 mo"),
            ("Agriculture · Local SEO", "2025", "A Rewari agri-input retailer", "GBP overhaul, commodity pages, and Hindi content. Page-1 for 16 agri-input queries in 90 days.", "16", "agri-input queries on page-1"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Rewari?", "Rewari is a low-competition market — most clients see measurable movement in 30-60 days. Brass B2B clients see RFQ enquiries within 60-90 days. Agriculture commodity clients see trader enquiries during peak season (Oct-Mar)."),
            ("Do you work with Rewari's brass industry?", "Yes — brassware manufacturers, exporters, and B2B traders are core verticals. We build product pages, B2B schema, and Hindi-English keyword targeting that rank for the queries your domestic and international buyers run."),
        ],
        "testimonial_city_specific": "Our brass export business was invisible to Gulf and US buyers. NEXUS built product pages, added B2B schema, ranked us on page-1 for every brassware query, and our inbound RFQ pipeline is now 4× what it was.",
        "testimonial_author": "Pradeep Yadav",
        "testimonial_role": "Partner, Brass Exporter · Rewari",
        "testimonial_avatar": "PY",
        "pricing_desc_local": "For single-location Rewari businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Rewari businesses expanding across NCR with bilingual content.",
        "pricing_desc_authority": "For Rewari brass groups, logistics companies, and B2B brands going pan-Haryana.",
        "siblings": [
            ("Gurugram", "Corporate, SaaS, fintech, real estate"),
            ("Mahendragarh", "Mining, agriculture, Aravalli tourism"),
            ("Jhajjar", "AIIMS, industrial corridor, agriculture"),
            ("Charkhi Dadri", "Newest district, stone-crushing, agriculture"),
        ],
    },
    {
        "slug": "rohtak",
        "display_name": "Rohtak",
        "lat": "28.8955",
        "lng": "76.6066",
        "postal_prefix": "124",
        "tagline": "Education hub · agriculture · healthcare",
        "hero_sub": "Rohtak local SEO — engineered to rank your business on Google. Education hub, agriculture, healthcare — captured with the SERP precision that wins tier-2 markets.",
        "eyebrow_left": "Rohtak · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / rohtak",
        "hero_stat_1_target": "13",
        "title": "SEO Agency in Rohtak — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Rohtak. We rank coaching institutes, agri-businesses, and healthcare brands on Google — with the local intelligence that wins tier-2 markets.",
        "og_description": "Local SEO in Rohtak — education hub, agriculture, healthcare.",
        "twitter_description": "Local SEO for Rohtak. Coaching, agriculture, and healthcare businesses ranked on page-1 of Google.",
        "why_features": [
            ("University & coaching cluster", "Rohtak's IIM, PGIMS, and the surrounding coaching belt drive constant parent-intent queries. We rank courses, faculty, and institutes on page-1 with admission-intent content."),
            ("Agricultural mandi queries", "Rohtak's mandi is one of Haryana's largest. We build commodity pages, mandi price schema, and Hindi keyword targeting for wheat, mustard, cotton, and bajra."),
            ("Multi-specialty healthcare", "PGIMS and a dozen private hospitals drive thousands of medical queries. We rank doctors, departments, and procedures on page-1 with patient-intent content and schema."),
            ("Hindi search dominance", "Rohtak is Hindi-dominant. We optimise Hindi keyword targeting, build Hindi content, and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Education · Local SEO", "2026", "A Rohtak coaching institute expanding to Sonipat and Jhajjar", "City-targeted pages, course schema, and faculty profiles. 4× admission enquiries in 5 months.", "4×", "admission enquiries / 5 mo"),
            ("Healthcare · Local SEO", "2025", "A Rohtak multi-specialty hospital", "Doctor-profile schema, procedure pages, and Hindi keyword targeting. 5× organic appointment requests in 4 months.", "5×", "appointment requests / 4 mo"),
            ("Agriculture · Cooperative SEO", "2025", "A Rohtak district marketing cooperative", "Commodity pages, member profiles, and mandi price schema. 4× buyer enquiries from across north India.", "4×", "buyer enquiries / quarter"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Rohtak?", "Most Rohtak clients see measurable movement in 30-60 days. Coaching clients see admission-intent traffic during admission season (Jan-Apr). Healthcare clients see appointment requests year-round."),
            ("Do you work with Rohtak's coaching institutes?", "Yes — IIT-JEE, NEET, SSC, banking, and state-PSC coaching are core verticals. We build course-targeted pages, faculty profiles, and admission-intent content that rank on page-1 and convert during admission season."),
        ],
        "testimonial_city_specific": "Our coaching institute was buried on page-3. NEXUS rebuilt our city pages, added faculty profiles, and we hit page-1 for 40+ course-intent queries in four months. Admissions doubled during the next cycle.",
        "testimonial_author": "Rajesh Hooda",
        "testimonial_role": "Director, Coaching Institute · Rohtak",
        "testimonial_avatar": "RH",
        "pricing_desc_local": "For single-location Rohtak businesses ready to dominate local search.",
        "pricing_desc_growth": "For Rohtak businesses expanding across Haryana and capturing coaching/healthcare intent.",
        "pricing_desc_authority": "For Rohtak education groups, hospital brands, and pan-Haryana market-entry plays.",
        "siblings": [
            ("Jhajjar", "AIIMS, industrial corridor, agriculture"),
            ("Bhiwani", "Wrestling & sports, agriculture"),
            ("Hisar", "Education hub, agriculture, retail"),
            ("Sonipat", "Education, real estate, NCR spillover"),
        ],
    },
    {
        "slug": "sirsa",
        "display_name": "Sirsa",
        "lat": "29.5350",
        "lng": "75.0290",
        "postal_prefix": "125",
        "tagline": "Border trade · agriculture · local services",
        "hero_sub": "Sirsa local SEO — engineered to rank your business on Google. Border trade, agriculture, local services — with the local intelligence that wins the cotton belt.",
        "eyebrow_left": "Sirsa · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / sirsa",
        "hero_stat_1_target": "9",
        "title": "SEO Agency in Sirsa — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Sirsa. We rank border-trade businesses, agriculture cooperatives, and local service brands on Google — with the Punjabi-Hindi bilingual intelligence that wins.",
        "og_description": "Local SEO in Sirsa — border trade, agriculture, local services.",
        "twitter_description": "Local SEO for Sirsa. Border trade, agriculture, and local service businesses ranked on page-1 of Google.",
        "why_features": [
            ("Indo-Pak border trade SEO", "Sirsa's Attari-Wagah spillover and the border-district economy drive unique B2B queries. We rank traders, transporters, and wholesale buyers on Google with route-targeted content."),
            ("Cotton & rice commodity SEO", "Sirsa is a cotton-rice belt. We build commodity landing pages, mandi price schema, and Hindi-Punjabi keyword targeting that rank during peak season."),
            ("Border-district local search", "Border-district buyers search with unique intent — defence, security, customs, and trade queries. We rank these businesses on Google with bilingual content and authority schema."),
            ("Punjabi-Hindi bilingual", "Sirsa is Punjabi-Hindi bilingual. We map queries in both languages, build parallel content, and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Border trade · B2B SEO", "2026", "A Sirsa border-trade wholesaler", "Route-targeted pages, commodity content, and Punjabi-Hindi keyword targeting. 3× inbound RFQs from Punjab and Rajasthan buyers.", "3×", "buyer RFQs / quarter"),
            ("Agriculture · Cooperative SEO", "2025", "A Sirsa district marketing cooperative", "Commodity pages, member profiles, and mandi price schema. 4× buyer enquiries from across north India.", "4×", "buyer enquiries / quarter"),
            ("Local services · GBP", "2025", "A Sirsa Sadar home-services brand", "GBP overhaul, photo cadence, and review velocity build. 3× local pack impressions in 4 months.", "+3×", "local pack impressions"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Sirsa?", "Sirsa is a low-competition market — most clients see measurable movement in 30-60 days. Agriculture commodity clients see trader enquiries during peak season (Oct-Mar). Border-trade clients see RFQ enquiries in 60-90 days."),
            ("Do you work with Sirsa's border-trade businesses?", "Yes — border traders, transporters, and wholesale buyers are core verticals. We build route-targeted pages, commodity content, and Punjabi-Hindi keyword targeting that rank for the queries your B2B buyers run."),
        ],
        "testimonial_city_specific": "Our border-trade business was invisible to Punjab and Rajasthan buyers. NEXUS built route-targeted pages, added commodity content, ranked us on page-1 for every border-trade query, and our inbound RFQ pipeline is now 3× what it was.",
        "testimonial_author": "Balwinder Singh",
        "testimonial_role": "Owner, Border Trade Business · Sirsa",
        "testimonial_avatar": "BS",
        "pricing_desc_local": "For single-location Sirsa businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Sirsa businesses expanding across the cotton belt with bilingual Punjabi-Hindi content.",
        "pricing_desc_authority": "For Sirsa border-trade groups, agri-businesses, and B2B brands going pan-Haryana.",
        "siblings": [
            ("Fatehabad", "Agriculture, cotton, mustard"),
            ("Hisar", "Education hub, agriculture, retail"),
            ("Jind", "Agriculture, cotton, local services"),
            ("Bhiwani", "Wrestling & sports, agriculture"),
        ],
    },
    {
        "slug": "sonipat",
        "display_name": "Sonipat",
        "lat": "28.9931",
        "lng": "77.0151",
        "postal_prefix": "131",
        "tagline": "Education · real estate · NCR spillover · agri-tech",
        "hero_sub": "Sonipat local SEO — engineered to rank your business on Google. Education, real estate, NCR spillover, agri-tech — captured with the SERP precision that wins tier-2 markets.",
        "eyebrow_left": "Sonipat · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / sonipat",
        "hero_stat_1_target": "14",
        "title": "SEO Agency in Sonipat — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Sonipat. We rank universities, K-12 schools, real estate developers, and agri-tech brands on Google — with the NCR-spillover intelligence that wins tier-2 markets.",
        "og_description": "Local SEO in Sonipat — education, real estate, NCR spillover, agri-tech.",
        "twitter_description": "Local SEO for Sonipat. Education, real estate, NCR spillover, and agri-tech businesses ranked on page-1 of Google.",
        "why_features": [
            ("University & education hub", "Sonipat's Ashoka University, O.P. Jindal Global University, and the surrounding coaching belt drive constant parent-intent queries. We rank courses, faculty, and institutes on page-1."),
            ("NCR real estate spillover", "Sonipat absorbs Delhi-NCR demand — buyers search 'property in Sonipat', 'flat near Delhi', 'plot on NH-44'. We capture this with locality-targeted pages and RERA schema."),
            ("Agri-tech & food processing", "Sonipat's food-processing and agri-tech cluster is one of Haryana's largest. We rank agri-tech brands, food processors, and B2B buyers on Google with capability pages and certifications schema."),
            ("English-Hindi bilingual", "Sonipat is English-Hindi bilingual. We map queries in both languages, build parallel content, and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Education · Local SEO", "2026", "A Sonipat K-12 school expanding admissions", "Programme pages, faculty profiles, and Hindi keyword targeting. 3× admission enquiries in 5 months.", "3×", "admission enquiries / 5 mo"),
            ("Real estate · Local SEO", "2025", "A Sonipat builder with 3 projects", "Locality-targeted pages, RERA schema, and developer-profile content. Page-1 for 24 high-intent property queries.", "24", "property queries on page-1"),
            ("Agri-tech · B2B SEO", "2025", "A Sonipat food-processing company", "Capability pages, certifications schema, and B2B content. 3× inbound RFQs from NCR retailers in 6 months.", "3×", "NCR RFQs / 6 mo"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Sonipat?", "Most Sonipat clients see measurable movement in 30-60 days. Education clients see admission-intent traffic during admission season (Jan-Apr). Real estate and agri-tech clients see leads year-round."),
            ("Do you work with Sonipat's education sector?", "Yes — universities, K-12 schools, playschools, and coaching institutes are core verticals. We build programme pages, faculty profiles, and admission-intent content that rank on page-1 and convert during admission season."),
        ],
        "testimonial_city_specific": "Our K-12 school was losing admissions to NCR schools despite being closer. NEXUS rebuilt our programme pages, added faculty profiles, ranked us on page-1 for every Sonipat-admission query, and our admission enquiries tripled in five months.",
        "testimonial_author": "Dr. Shalini Verma",
        "testimonial_role": "Principal, K-12 School · Sonipat",
        "testimonial_avatar": "SV",
        "pricing_desc_local": "For single-location Sonipat businesses ready to dominate local search.",
        "pricing_desc_growth": "For Sonipat businesses expanding across NCR and capturing education/real-estate intent.",
        "pricing_desc_authority": "For Sonipat education groups, real estate developers, and pan-NCR brands.",
        "siblings": [
            ("Panipat", "Textile capital, home textiles, B2B"),
            ("Jind", "Agriculture, cotton, local services"),
            ("Rohtak", "Education hub, agriculture, healthcare"),
            ("Jhajjar", "AIIMS, industrial corridor, agriculture"),
        ],
    },
    {
        "slug": "yamunanagar",
        "display_name": "Yamunanagar",
        "lat": "30.1290",
        "lng": "77.2960",
        "postal_prefix": "135",
        "tagline": "Timber/plywood industry · agriculture",
        "hero_sub": "Yamunanagar local SEO — engineered to rank your business on Google. Timber/plywood industry, agriculture, and industrial cluster B2B — with the SERP precision that wins B2B markets.",
        "eyebrow_left": "Yamunanagar · Haryana · SEO",
        "eyebrow_right": "/ seo / haryana / yamunanagar",
        "hero_stat_1_target": "10",
        "title": "SEO Agency in Yamunanagar — NEXUS Local SEO",
        "description": "NEXUS is a local SEO agency in Yamunanagar. We rank timber/plywood manufacturers, agri-businesses, and industrial-cluster B2B brands on Google — with the local intelligence that wins.",
        "og_description": "Local SEO in Yamunanagar — timber/plywood industry, agriculture, industrial cluster B2B.",
        "twitter_description": "Local SEO for Yamunanagar. Timber/plywood manufacturers, agri-businesses, and industrial-cluster B2B brands ranked.",
        "why_features": [
            ("Timber & plywood B2B SEO", "Yamunanagar's timber and plywood cluster is one of India's largest. We rank manufacturers, suppliers, and B2B buyers on Google with product pages, B2B schema, and Hindi keyword targeting."),
            ("Agricultural commodity queries", "Sugarcane, wheat, and rice drive constant search. We build commodity pages, mandi price schema, and Hindi-Punjabi keyword targeting that rank during peak season."),
            ("Industrial cluster SEO", "Yamunanagar's industrial cluster (paper, chemicals, sugar) generates thousands of B2B queries. We rank suppliers, dealers, and service providers on Google with capability pages and certifications schema."),
            ("Hindi-Punjabi bilingual", "Yamunanagar is Hindi-Punjabi bilingual. We map queries in both languages, build parallel content, and use hreflang-style signals so Google serves the right variant to the right user."),
        ],
        "case_vignettes": [
            ("Timber · B2B SEO", "2026", "A Yamunanagar plywood manufacturer", "Product pages, B2B schema, and Hindi keyword targeting. 4× inbound RFQs from NCR and Punjab buyers.", "4×", "NCR/Punjab RFQs / quarter"),
            ("Agriculture · Cooperative SEO", "2025", "A Yamunanagar district marketing cooperative", "Commodity pages, member profiles, and mandi price schema. 3× buyer enquiries from across north India.", "3×", "buyer enquiries / quarter"),
            ("Industrial · B2B SEO", "2025", "A Yamunanagar paper-mill supplier", "Capability pages, certifications schema, and B2B content. Page-1 for 14 industrial-supply queries in 6 months.", "14", "industrial queries on page-1"),
        ],
        "faq_extra": [
            ("How long does SEO take to show results in Yamunanagar?", "Most Yamunanagar clients see measurable movement in 30-60 days. Timber B2B clients see RFQ enquiries within 60-90 days. Agriculture commodity clients see trader enquiries during peak season (Oct-Mar)."),
            ("Do you work with Yamunanagar's timber/plywood businesses?", "Yes — timber, plywood, and panel-manufacturing businesses are core verticals. We build product pages, B2B schema, and Hindi keyword targeting that rank for the queries your domestic and international buyers run."),
        ],
        "testimonial_city_specific": "Our plywood business was invisible to NCR and Punjab buyers. NEXUS built product pages, added B2B schema, ranked us on page-1 for every plywood query, and our inbound RFQ pipeline is now 4× what it was.",
        "testimonial_author": "Ashok Bansal",
        "testimonial_role": "Director, Plywood Manufacturer · Yamunanagar",
        "testimonial_avatar": "AB",
        "pricing_desc_local": "For single-location Yamunanagar businesses claiming first-mover local rankings.",
        "pricing_desc_growth": "For Yamunanagar businesses expanding across NCR and Punjab with bilingual content.",
        "pricing_desc_authority": "For Yamunanagar timber groups, agri-businesses, and B2B brands going pan-India.",
        "siblings": [
            ("Kurukshetra", "Religious tourism, education, agriculture"),
            ("Karnal", "Rice trade, agriculture, education"),
            ("Ambala", "Defence cantonment, healthcare, retail"),
            ("Panchkula", "Premium real estate, hospitality, retail"),
        ],
    },
]
